// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuk_B7U5nvJp6yUQ3zZ6Cc79g_FBGWwvY',
    appId: '1:997867792617:web:a76c8910031fbdc28da878',
    messagingSenderId: '997867792617',
    projectId: 'notetaker-backend',
    authDomain: 'notetaker-backend.firebaseapp.com',
    storageBucket: 'notetaker-backend.appspot.com',
    measurementId: 'G-SQ209YYWEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDniLojC2hcaRjnoVum0uabZBxmyjg4kNA',
    appId: '1:997867792617:android:a6b3fae4a04fbac68da878',
    messagingSenderId: '997867792617',
    projectId: 'notetaker-backend',
    storageBucket: 'notetaker-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJpXIiqXzNQZ9kgf6ZTga7KEcrGD4tgMQ',
    appId: '1:997867792617:ios:9ca861dd02c3b0988da878',
    messagingSenderId: '997867792617',
    projectId: 'notetaker-backend',
    storageBucket: 'notetaker-backend.appspot.com',
    iosClientId: '997867792617-ae15f18dvn48h1aqh9qr7uhhpmclel00.apps.googleusercontent.com',
    iosBundleId: 'np.firststuff.notetaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJpXIiqXzNQZ9kgf6ZTga7KEcrGD4tgMQ',
    appId: '1:997867792617:ios:9ca861dd02c3b0988da878',
    messagingSenderId: '997867792617',
    projectId: 'notetaker-backend',
    storageBucket: 'notetaker-backend.appspot.com',
    iosClientId: '997867792617-ae15f18dvn48h1aqh9qr7uhhpmclel00.apps.googleusercontent.com',
    iosBundleId: 'np.firststuff.notetaker',
  );
}
